n1 = int(input ('Digite um número: '))
n2 = int(input('Digite outro número: '))
n3 = int(input('Digite mais um número: '))
n4 = int(input ('Digite o último número: '))
print(f'Você digitou os valores : {n1,n2,n3,n4}')
n5 = (n1, n2, n3, n4 )
print(f'O valor 9 apareceu {(n5.count(9))} vezes')
print(f'O valor 3 apareceu na {(n5.index(3)+1)}ª posição')
n6 = (n1%2, n2%2, n3%2, n4%2)
print(f'Os valores pares digitados foram {(n6.count(0))}')